name: Deploy CI

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: npm install

      - name: build
        run: yarn add umi-plugin-antd-theme umi-plugin-pro && npm run site

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          GA_KEY: UA-72788897-6
          ANT_DESIGN_PRO_ONLY_DO_NOT_USE_IN_YOUR_PRODUCTION: site
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTION_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
        with:
          emptyCommits: false
